'use strict';
const { getDb } = require('./init');
const db = getDb();

const insert = db.prepare(`INSERT OR IGNORE INTO pages (slug, title, meta_description, h1, hero_subtitle, content_json, updated_at) VALUES (?, ?, ?, ?, ?, ?, datetime('now'))`);

const pages = [];

// ─── HUB TARNOBRZEG ────────────────────────────────────────
pages.push({
  slug: 'tarnobrzeg',
  title: 'Marketing cyfrowy w Tarnobrzegu — Halo Agencja',
  meta_description: 'Agencja marketingu cyfrowego w Tarnobrzegu — Halo. Strony internetowe, SEO, Google Ads, social media i automatyzacje dla firm z Tarnobrzegu i regionu.',
  h1: 'Marketing cyfrowy w Tarnobrzegu',
  hero_subtitle: 'Kompleksowe usługi marketingowe dla firm z Tarnobrzegu i okolic. SEO, Google Ads, strony internetowe, social media i automatyzacje.',
  content_json: { opis: 'Halo to agencja marketingu cyfrowego z Tarnobrzegu. Pomagam lokalnym firmom rosnąć w internecie — od budowy strony, przez pozycjonowanie, po płatne kampanie i automatyzacje sprzedaży.', uslugi: ['strony-internetowe','seo','google-ads','grafika-reklamowa','automatyzacje','marketing-internetowy','social-media','content-marketing','analityka-doradztwo','sklep-internetowy'] }
});

// ─── LOKALIZACJE ───────────────────────────────────────────
pages.push({
  slug: 'lokalizacje',
  title: 'Obsługiwane lokalizacje — Halo Agencja Marketingowa',
  meta_description: 'Agencja Halo obsługuje firmy z Tarnobrzegu, Stalowej Woli, Sandomierza, Mielca, Rzeszowa i Nowej Dęby. Sprawdź usługi dla Twojego miasta.',
  h1: 'Obsługiwane lokalizacje',
  hero_subtitle: 'Świadczę usługi marketingu cyfrowego dla firm z Tarnobrzegu, Stalowej Woli, Sandomierza, Mielca, Rzeszowa i Nowej Dęby.',
  content_json: { opis: 'Działam lokalnie, ale myślę globalnie. Obsługuję firmy z całego regionu tarnobrzeskiego i podkarpackiego.', miasta: ['tarnobrzeg','stalowa-wola','sandomierz','mielec','rzeszow','nowa-deba'] }
});

// ─── KATEGORIE TARNOBRZEG (poziom 2) ──────────────────────
const categories = [
  {
    slug: 'tarnobrzeg/strony-internetowe',
    title: 'Strony internetowe Tarnobrzeg — Halo',
    meta_description: 'Profesjonalne strony internetowe dla firm z Tarnobrzegu. Projekt graficzny, SEO on-page, responsywność, szybkość. Bezpłatna konsultacja.',
    h1: 'Strony internetowe\ndla firm z Tarnobrzegu',
    hero_subtitle: 'Tworzę nowoczesne, szybkie i skutecznie pozycjonowane strony internetowe dla firm z Tarnobrzegu i regionu.',
    content_json: {
      dla_kogo: 'Dla firm lokalnych, usługodawców, sklepów i przedsiębiorców z Tarnobrzegu i okolic szukających profesjonalnej obecności w internecie.',
      co_obejmuje: ['Projekt graficzny dopasowany do marki','Responsywny kod zoptymalizowany pod mobile','Pełne SEO on-page','Integracja z GA4 i Search Console','Panel administracyjny','SSL, hosting i kopie zapasowe','Formularze kontaktowe','Automatyzacja follow-up po formularzu'],
      korzysci: ['Strona widoczna w Google na frazy lokalne','Profesjonalny wizerunek firmy w internecie','Więcej zapytań od klientów z Tarnobrzegu','Strona działająca szybko na każdym urządzeniu'],
      faq: [{pytanie:'Ile kosztuje strona internetowa w Tarnobrzegu?',odpowiedz:'Koszt zależy od zakresu projektu. Wycenę przygotowuję indywidualnie po bezpłatnej konsultacji.'},{pytanie:'Jak długo trwa realizacja strony?',odpowiedz:'Standardowo 3–5 tygodni od momentu zebrania materiałów.'},{pytanie:'Czy mogę samodzielnie edytować stronę po oddaniu?',odpowiedz:'Tak, każda strona jest wyposażona w panel administracyjny.'}],
      powiazane_uslugi: ['tarnobrzeg/seo','tarnobrzeg/google-ads','tarnobrzeg/automatyzacje']
    }
  },
  {
    slug: 'tarnobrzeg/seo',
    title: 'SEO Tarnobrzeg — pozycjonowanie lokalne — Halo',
    meta_description: 'Pozycjonowanie lokalne SEO w Tarnobrzegu. Audyt, optymalizacja Google Business Profile, treści SEO, link building. Sprawdź ofertę.',
    h1: 'Pozycjonowanie lokalne SEO\nw Tarnobrzegu',
    hero_subtitle: 'Pomagam firmom z Tarnobrzegu pojawiać się wyżej w Google — na frazy lokalne, które przynoszą klientów.',
    content_json: {
      dla_kogo: 'Dla firm z Tarnobrzegu chcących zdobywać klientów z lokalnych wyszukiwań w Google.',
      co_obejmuje: ['Audyt SEO i analiza konkurencji','Google Business Profile','Lokalne słowa kluczowe','Optymalizacja techniczna','Treści SEO i landing pages','Link building lokalny','Zarządzanie opiniami Google','Miesięczny raport'],
      korzysci: ['Wyższe pozycje na frazy lokalne w Tarnobrzegu','Więcej organicznych odwiedzin bez kosztów reklamy','Silna wizytówka Google z opiniami','Wzrost zaufania wśród lokalnych klientów'],
      faq: [{pytanie:'Kiedy zobaczę efekty pozycjonowania?',odpowiedz:'Pierwsze efekty widoczne są po 2–3 miesiącach. Pełne rezultaty po 4–6 miesiącach regularnej pracy.'},{pytanie:'Czy SEO lokalne różni się od standardowego?',odpowiedz:'Tak — SEO lokalne koncentruje się na frazach z nazwą miasta i optymalizacji wizytówki Google Maps.'}],
      powiazane_uslugi: ['tarnobrzeg/strony-internetowe','tarnobrzeg/content-marketing','tarnobrzeg/analityka-doradztwo']
    }
  },
  {
    slug: 'tarnobrzeg/google-ads',
    title: 'Google Ads Tarnobrzeg — kampanie reklamowe — Halo',
    meta_description: 'Kampanie Google Ads dla firm z Tarnobrzegu. Konfiguracja, optymalizacja, śledzenie konwersji i remarketing. Wyniki mierzone w ROAS.',
    h1: 'Google Ads\ndla firm z Tarnobrzegu',
    hero_subtitle: 'Prowadzę kampanie Google Ads przynoszące mierzalny zwrot z inwestycji — dla firm z Tarnobrzegu i regionu.',
    content_json: {
      dla_kogo: 'Dla firm z Tarnobrzegu chcących szybko dotrzeć do klientów szukających ich usług w Google.',
      co_obejmuje: ['Audyt konta lub konfiguracja nowego','Badanie słów kluczowych','Kreacje reklamowe','Targetowanie lokalne','Śledzenie konwersji','Tygodniowa optymalizacja','Remarketing','Miesięczny raport ROAS'],
      korzysci: ['Natychmiastowy ruch na stronie','Precyzyjne dotarcie do lokalnych klientów','Pełna kontrola budżetu reklamowego','Mierzalne wyniki — leady, telefony, sprzedaż'],
      faq: [{pytanie:'Jaki budżet potrzebny na Google Ads w Tarnobrzegu?',odpowiedz:'Dla lokalnych firm rekomenduję start od 500–800 zł/mies. budżetu reklamowego. Opłata za zarządzanie jest osobna.'},{pytanie:'Jak szybko widać efekty kampanii?',odpowiedz:'Pierwsze kliknięcia i zapytania pojawiają się już w ciągu kilku godzin od uruchomienia kampanii.'}],
      powiazane_uslugi: ['tarnobrzeg/marketing-internetowy','tarnobrzeg/seo','tarnobrzeg/analityka-doradztwo']
    }
  },
  {
    slug: 'tarnobrzeg/grafika-reklamowa',
    title: 'Grafika reklamowa i branding Tarnobrzeg — Halo',
    meta_description: 'Grafika reklamowa i identyfikacja wizualna dla firm z Tarnobrzegu. Logo, bannery, social media, ulotki, brandbook. Wycena indywidualna.',
    h1: 'Grafika reklamowa i branding\ndla firm z Tarnobrzegu',
    hero_subtitle: 'Tworzę spójną identyfikację wizualną i materiały reklamowe, które wyróżniają firmy z Tarnobrzegu na tle konkurencji.',
    content_json: {
      dla_kogo: 'Dla firm z Tarnobrzegu budujących lub odświeżających swój wizerunek — od logotypu po pełny brandbook.',
      co_obejmuje: ['Logo i identyfikacja wizualna','Bannery Google Display i Meta','Szablony social media','Ulotki, plakaty, roll-upy','Wizytówki i materiały biurowe','Prezentacje firmowe','Grafiki na stronę','Brandbook'],
      korzysci: ['Spójny wizerunek we wszystkich kanałach','Profesjonalne materiały gotowe do druku i online','Wyróżnienie na tle lokalnej konkurencji','Oszczędność czasu na tworzeniu materiałów'],
      faq: [{pytanie:'Czy mogę zamówić sam logotyp bez pełnego brandingu?',odpowiedz:'Tak, realizuję zarówno kompleksowe projekty jak i pojedyncze materiały.'},{pytanie:'W jakich formatach otrzymam pliki?',odpowiedz:'Dostarczam pliki w formatach AI/PDF do druku oraz PNG/SVG do użytku online.'}],
      powiazane_uslugi: ['tarnobrzeg/social-media','tarnobrzeg/strony-internetowe','tarnobrzeg/content-marketing']
    }
  },
  {
    slug: 'tarnobrzeg/automatyzacje',
    title: 'Automatyzacje firmowe Tarnobrzeg — Halo',
    meta_description: 'Automatyzacje procesów biznesowych dla firm z Tarnobrzegu. Make, Zapier, chatboty AI, CRM, follow-up. Wycena indywidualna.',
    h1: 'Automatyzacje firmowe\ndla przedsiębiorców z Tarnobrzegu',
    hero_subtitle: 'Automatyzuję powtarzalne procesy w firmach z Tarnobrzegu — od follow-upów po integracje systemów i chatboty AI.',
    content_json: {
      dla_kogo: 'Dla właścicieli firm z Tarnobrzegu, którzy chcą oszczędzać czas i obsługiwać więcej klientów bez zwiększania etatów.',
      co_obejmuje: ['Audyt procesów do automatyzacji','Make (Integromat) i Zapier','Chatboty AI','Follow-up email i SMS','Integracje CRM','Automatyzacja fakturowania','Powiadomienia i alerty','Szkolenie z obsługi'],
      korzysci: ['Oszczędność kilku godzin dziennie','Brak przeoczonych zapytań od klientów','Automatyczna obsługa rutynowych zadań','Skalowalność bez zatrudniania pracowników'],
      faq: [{pytanie:'Od czego zacząć automatyzację w firmie?',odpowiedz:'Od audytu procesów — identyfikujemy co zajmuje najwięcej czasu i przynosi największy zysk z automatyzacji.'},{pytanie:'Czy potrzebuję wiedzy technicznej?',odpowiedz:'Nie. Buduję systemy z myślą o prostej obsłudze i szkolę z ich użytkowania.'}],
      powiazane_uslugi: ['tarnobrzeg/strony-internetowe','tarnobrzeg/analityka-doradztwo','tarnobrzeg/marketing-internetowy']
    }
  },
  {
    slug: 'tarnobrzeg/marketing-internetowy',
    title: 'Marketing internetowy Tarnobrzeg — Halo',
    meta_description: 'Marketing internetowy dla firm z Tarnobrzegu. Google Ads, Facebook Ads, TikTok Ads, LinkedIn. Kompleksowe kampanie płatne z mierzalnymi wynikami.',
    h1: 'Marketing internetowy\ndla firm z Tarnobrzegu',
    hero_subtitle: 'Prowadzę kompleksowe kampanie marketingowe w Google, Facebooku, Instagramie, TikToku i LinkedIn dla firm z Tarnobrzegu.',
    content_json: {
      dla_kogo: 'Dla firm z Tarnobrzegu chcących dotrzeć do klientów przez płatne kanały reklamowe online.',
      co_obejmuje: ['Kampanie Google Ads','Facebook i Instagram Ads','TikTok Ads','LinkedIn Ads','Planowanie mediamix','Kreacje reklamowe','Konfiguracja pikseli i konwersji','Raport miesięczny'],
      korzysci: ['Dotarcie do precyzyjnie dobranej grupy docelowej','Szybkie efekty — leady i sprzedaż','Pełna transparentność wyników','Elastyczność budżetu reklamowego'],
      faq: [{pytanie:'Które kanały reklamowe są najlepsze dla firm z Tarnobrzegu?',odpowiedz:'Zależy od branży. Dla usług lokalnych — Google Ads. Dla budowania marki i produktów — Meta. Dla B2B — LinkedIn.'},{pytanie:'Czy można prowadzić kampanie na kilku platformach jednocześnie?',odpowiedz:'Tak i często to optymalny model — tworzę spójną strategię omnichannel.'}],
      powiazane_uslugi: ['tarnobrzeg/google-ads','tarnobrzeg/social-media','tarnobrzeg/analityka-doradztwo']
    }
  },
  {
    slug: 'tarnobrzeg/social-media',
    title: 'Social media Tarnobrzeg — prowadzenie profili — Halo',
    meta_description: 'Prowadzenie social media dla firm z Tarnobrzegu. Facebook, Instagram, TikTok. Posty, rolki, stories, kampanie reklamowe. Wycena indywidualna.',
    h1: 'Social media\ndla firm z Tarnobrzegu',
    hero_subtitle: 'Prowadzę profile firmowe w mediach społecznościowych dla firm z Tarnobrzegu — regularnie, konsekwentnie i z wynikami.',
    content_json: {
      dla_kogo: 'Dla firm z Tarnobrzegu chcących aktywnie budować społeczność i zasięgi w mediach społecznościowych.',
      co_obejmuje: ['Prowadzenie Facebooka i Instagrama','Posty, grafiki, rolki i stories','Kalendarz treści','Moderacja komentarzy i wiadomości','Zasięgi organiczne','Kampanie reklamowe','Raport miesięczny','Strategia per platforma'],
      korzysci: ['Regularna i profesjonalna komunikacja','Wzrost liczby obserwujących','Budowanie zaufania i rozpoznawalności','Więcej zapytań z social media'],
      faq: [{pytanie:'Jak często będą publikowane posty?',odpowiedz:'W zależności od pakietu — od 3 do 5 postów tygodniowo plus stories.'},{pytanie:'Czy dostaję dostęp do statystyk?',odpowiedz:'Tak, raz w miesiącu dostarczam raport z zasięgami, zaangażowaniem i wzrostem profilu.'}],
      powiazane_uslugi: ['tarnobrzeg/grafika-reklamowa','tarnobrzeg/content-marketing','tarnobrzeg/marketing-internetowy']
    }
  },
  {
    slug: 'tarnobrzeg/content-marketing',
    title: 'Content marketing Tarnobrzeg — teksty SEO — Halo',
    meta_description: 'Content marketing dla firm z Tarnobrzegu. Teksty na strony, artykuły blogowe SEO, copywriting, newslettery, e-booki. Wycena indywidualna.',
    h1: 'Content marketing\ndla firm z Tarnobrzegu',
    hero_subtitle: 'Tworzę treści, które przyciągają klientów z Google i budują autorytet firm z Tarnobrzegu w ich branży.',
    content_json: {
      dla_kogo: 'Dla firm z Tarnobrzegu chcących pozyskiwać klientów przez wartościowe treści w internecie.',
      co_obejmuje: ['Strategia contentowa','Teksty na strony usługowe (SEO copywriting)','Artykuły blogowe SEO','Opisy produktów i kategorii','Newslettery i sekwencje email','E-booki i checklisty','Copywriting i storytelling','Optymalizacja istniejących treści'],
      korzysci: ['Wyższe pozycje w Google na frazy long-tail','Budowanie eksperckiego wizerunku','Edukacja klientów zwiększająca konwersję','Treści pracujące przez lata'],
      faq: [{pytanie:'Czy treści są pisane pod SEO?',odpowiedz:'Tak, każdy tekst jest zoptymalizowany pod konkretne frazy kluczowe z uwzględnieniem intencji wyszukiwania.'},{pytanie:'Skąd wiecie, co pisać?',odpowiedz:'Zaczynam od analizy słów kluczowych i działań konkurencji, a następnie tworzę strategię contentową.'}],
      powiazane_uslugi: ['tarnobrzeg/seo','tarnobrzeg/social-media','tarnobrzeg/analityka-doradztwo']
    }
  },
  {
    slug: 'tarnobrzeg/analityka-doradztwo',
    title: 'Analityka i doradztwo marketingowe Tarnobrzeg — Halo',
    meta_description: 'Analityka marketingowa i doradztwo strategiczne dla firm z Tarnobrzegu. GA4, GTM, audyty, testy A/B, raporty z rekomendacjami.',
    h1: 'Analityka i doradztwo\nmarketingowe w Tarnobrzegu',
    hero_subtitle: 'Konfiguruję śledzenie, analizuję dane i doradza co zmieniać, żeby marketing firmy z Tarnobrzegu przynosił lepsze wyniki.',
    content_json: {
      dla_kogo: 'Dla firm z Tarnobrzegu chcących podejmować decyzje marketingowe w oparciu o dane, nie intuicję.',
      co_obejmuje: ['Konfiguracja GA4 i GTM','Śledzenie konwersji','Audyt działań marketingowych','Raporty z rekomendacjami','Testy A/B','Analiza lejka sprzedażowego','Doradztwo strategiczne','Konsultacje godzinowe'],
      korzysci: ['Jasny obraz co działa a co nie','Eliminacja budżetu marnowanego na nieefektywne działania','Decyzje oparte na danych','Wzrost efektywności kampanii'],
      faq: [{pytanie:'Czym jest GA4 i dlaczego warto go skonfigurować?',odpowiedz:'Google Analytics 4 to narzędzie śledzące ruch na stronie i konwersje. Bez niego działasz w ciemno.'},{pytanie:'Co to jest test A/B?',odpowiedz:'Porównywanie dwóch wersji strony lub reklamy, żeby wybrać tę przynoszącą więcej wyników.'}],
      powiazane_uslugi: ['tarnobrzeg/seo','tarnobrzeg/google-ads','tarnobrzeg/content-marketing']
    }
  },
  {
    slug: 'tarnobrzeg/sklep-internetowy',
    title: 'Sklep internetowy Tarnobrzeg — e-commerce — Halo',
    meta_description: 'Sklep internetowy dla firm z Tarnobrzegu. WooCommerce, PrestaShop, optymalizacja konwersji CRO, Google Shopping, SEO sklepu. Wycena.',
    h1: 'Sklep internetowy\ndla firm z Tarnobrzegu',
    hero_subtitle: 'Buduję i optymalizuję sklepy internetowe dla firm z Tarnobrzegu — od projektu po kampanie Google Shopping.',
    content_json: {
      dla_kogo: 'Dla firm z Tarnobrzegu chcących sprzedawać swoje produkty przez internet.',
      co_obejmuje: ['Wdrożenie WooCommerce/PrestaShop','Projekt graficzny sklepu','Optymalizacja konwersji CRO','Integracja płatności','Feed Google Merchant','SEO sklepu','Google Shopping','Audyt i optymalizacja'],
      korzysci: ['Sprzedaż 24/7 bez obsługi klienta','Dotarcie do klientów poza Tarnobrzegiem','Wzrost przychodów z kanału online','Zautomatyzowana obsługa zamówień'],
      faq: [{pytanie:'WooCommerce czy PrestaShop — co wybrać?',odpowiedz:'WooCommerce jest prostszy w obsłudze i polecany dla mniejszych sklepów. PrestaShop lepiej sprawdza się przy dużych katalogach.'},{pytanie:'Czy pomożesz w kampaniach reklamowych sklepu?',odpowiedz:'Tak, oferta obejmuje pełne prowadzenie kampanii Google Shopping i Meta Ads dla sklepu.'}],
      powiazane_uslugi: ['tarnobrzeg/seo','tarnobrzeg/google-ads','tarnobrzeg/automatyzacje']
    }
  },
];

pages.push(...categories.map(c => ({ ...c, content_json: c.content_json })));

// ─── LEVEL-3 SUBPAGES ─────────────────────────────────────

const sub3 = [
// STRONY INTERNETOWE
{s:'tarnobrzeg/strony-internetowe/projekt-graficzny-strony',t:'Projekt graficzny strony internetowej Tarnobrzeg',m:'Projekt graficzny strony internetowej dla firm z Tarnobrzegu. Nowoczesny design dopasowany do marki i branży. Wycena indywidualna.',h:'Projekt graficzny strony\ninternetowej w Tarnobrzegu',sub:'Tworzę projekty graficzne stron internetowych, które przykuwają uwagę i budują zaufanie do firm z Tarnobrzegu.',o:'Projekt graficzny to fundament skutecznej strony internetowej. Tworzę unikalny design dopasowany do charakteru firmy, branży i oczekiwań klientów z lokalnego rynku tarnobrzeskiego. Każdy projekt zaczyna się od analizy konkurencji i oczekiwań docelowej grupy odbiorców.',k:['Unikalny design wyróżniający firmę na tle konkurencji','Projekt oparty o psychologię kolorów i UX','Responsywny — wygląda świetnie na każdym urządzeniu','Spójny z resztą identyfikacji wizualnej firmy'],f:[{p:'Jak długo trwa projekt graficzny strony?',o:'Projekt graficzny (mockupy) zajmuje zwykle 5–10 dni roboczych.'},{p:'Czy mogę zobaczyć projekt przed wdrożeniem?',o:'Tak — na etapie mockupów prezentuję projekt do akceptacji przed przystąpieniem do kodowania.'}],par:'tarnobrzeg/strony-internetowe'},
{s:'tarnobrzeg/strony-internetowe/responsywny-kod-mobile',t:'Responsywna strona mobilna Tarnobrzeg',m:'Responsywne strony internetowe zoptymalizowane pod urządzenia mobilne dla firm z Tarnobrzegu. Mobile-first, szybkie ładowanie.',h:'Responsywna strona mobilna\ndla firm z Tarnobrzegu',sub:'Ponad 60% użytkowników przegląda internet na telefonie. Tworzę strony, które działają perfekcyjnie na każdym urządzeniu.',o:'Responsywność to dziś standard, ale dobry kod mobilny to coś więcej. Buduję strony z podejściem mobile-first — najpierw optymalizuję pod telefon, potem pod desktop. Efektem jest strona ładująca się błyskawicznie i wyglądająca świetnie na każdym ekranie.',k:['Perfekcyjne działanie na telefonach i tabletach','Szybkie ładowanie na połączeniach mobilnych','Lepsze pozycje w Google (mobile-first indexing)','Niższy wskaźnik odrzuceń'],f:[{p:'Co to jest mobile-first indexing?',o:'Google indeksuje strony w oparciu o wersję mobilną. Strona nieoptymalna na telefon traci pozycje.'},{p:'Jak sprawdzić czy moja strona jest responsywna?',o:'Można użyć narzędzia Google Mobile-Friendly Test lub po prostu otworzyć stronę na telefonie.'}],par:'tarnobrzeg/strony-internetowe'},
{s:'tarnobrzeg/strony-internetowe/seo-on-page',t:'SEO on-page strony internetowej Tarnobrzeg',m:'SEO on-page dla stron internetowych firm z Tarnobrzegu. Optymalizacja meta tagów, nagłówków, szybkości i struktury. Lepsza widoczność w Google.',h:'SEO on-page strony\ninternetowej w Tarnobrzegu',sub:'Optymalizuję każdy element strony pod kątem algorytmów Google — meta tagi, nagłówki, szybkość, struktura URL.',o:'SEO on-page to optymalizacja elementów bezpośrednio na stronie internetowej. Obejmuje tytuły, opisy, nagłówki H1-H6, strukturę URL, prędkość ładowania i wewnętrzne linkowanie. Dla firm z Tarnobrzegu dodaję też optymalizację lokalną z nazwą miasta.',k:['Wyższe pozycje w wynikach wyszukiwania','Lepsza indeksacja przez Googlebot','Zwiększony ruch organiczny bez kosztów reklamy','Fundament pod długoterminowe SEO'],f:[{p:'Czym różni się SEO on-page od off-page?',o:'On-page to optymalizacja samej strony. Off-page to budowanie linków i autorytet zewnętrzny.'},{p:'Jak często trzeba odświeżać SEO on-page?',o:'Przy każdej większej zmianie treści lub struktury strony, a także przy aktualizacjach algorytmu Google.'}],par:'tarnobrzeg/strony-internetowe'},
{s:'tarnobrzeg/strony-internetowe/schema-markup',t:'Schema markup strony Tarnobrzeg',m:'Implementacja schema markup (danych strukturyzowanych) dla stron firm z Tarnobrzegu. Rich snippets, lepsza widoczność w Google.',h:'Schema markup\nstrony internetowej w Tarnobrzegu',sub:'Wdrażam dane strukturyzowane schema.org, dzięki którym strona wyróżnia się w wynikach wyszukiwania rich snippets.',o:'Schema markup to kod informujący Google o typie treści na stronie — czy to firma lokalna, produkt, artykuł czy FAQ. Dzięki schema Google może wyświetlać rozszerzone wyniki (gwiazdki, godziny otwarcia, ceny) już na stronie wyników wyszukiwania.',k:['Wyróżnienie w wynikach Google (rich snippets)','Wyższy CTR z wyników wyszukiwania','Lepsza interpretacja treści przez Google','Podstawa pod widoczność w AI Overviews'],f:[{p:'Jakie typy schema warto wdrożyć dla lokalnej firmy?',o:'LocalBusiness, FAQPage, BreadcrumbList, Review oraz Service — to priorytety dla firm lokalnych.'},{p:'Czy schema markup widać na stronie dla użytkownika?',o:'Nie — to kod niewidoczny dla odwiedzających, ale czytany przez wyszukiwarki.'}],par:'tarnobrzeg/strony-internetowe'},
{s:'tarnobrzeg/strony-internetowe/core-web-vitals',t:'Core Web Vitals strony Tarnobrzeg',m:'Optymalizacja Core Web Vitals dla stron firm z Tarnobrzegu. LCP, FID, CLS — szybkość i stabilność strony wpływająca na pozycje w Google.',h:'Core Web Vitals\nstrony internetowej w Tarnobrzegu',sub:'Optymalizuję wskaźniki Core Web Vitals — szybkość ładowania, interaktywność i stabilność layoutu strony.',o:'Core Web Vitals to zestaw wskaźników szybkości i użyteczności strony, które Google używa jako czynnik rankingowy. Obejmuje LCP (szybkość ładowania treści), FID/INP (czas reakcji) i CLS (stabilność layoutu). Niska ocena CWV = gorsze pozycje i wyższy wskaźnik odrzuceń.',k:['Wyższe pozycje w Google','Szybsza strona = więcej konwersji','Lepsza ocena PageSpeed Insights','Mniejszy bounce rate i więcej czasu na stronie'],f:[{p:'Co oznacza wynik Dobrze/Wymaga poprawy/Słabo w CWV?',o:'Dobrze oznacza LCP<2,5s, INP<200ms i CLS<0,1. Każdy element poza tymi progami negatywnie wpływa na ranking.'},{p:'Jak sprawdzić Core Web Vitals swojej strony?',o:'Narzędzia Google PageSpeed Insights i Search Console pokazują aktualne wyniki CWV.'}],par:'tarnobrzeg/strony-internetowe'},
{s:'tarnobrzeg/strony-internetowe/integracja-narzedzi-analitycznych',t:'Integracja GA4 i narzędzi analitycznych Tarnobrzeg',m:'Konfiguracja Google Analytics 4, Search Console i GTM dla stron firm z Tarnobrzegu. Śledzenie ruchu, zdarzeń i konwersji.',h:'Integracja narzędzi analitycznych\ndla firm z Tarnobrzegu',sub:'Konfiguruję GA4, Google Tag Manager i Search Console — żebyś dokładnie wiedział, kto odwiedza Twoją stronę i skąd pochodzi.',o:'Bez analityki działasz w ciemno. Konfiguruję pełen zestaw narzędzi pomiarowych: Google Analytics 4 do śledzenia ruchu i zachowań, Google Tag Manager do zarządzania tagami oraz Search Console do monitorowania pozycji i błędów indeksacji.',k:['Pełny obraz źródeł ruchu na stronie','Śledzenie jakie treści i podstrony działają najlepiej','Dane o konwersjach i zachowaniach użytkowników','Podstawa pod skuteczną optymalizację kampanii'],f:[{p:'Czym różni się GA4 od Universal Analytics?',o:'GA4 to nowa wersja Google Analytics oparta o zdarzenia zamiast sesji. UA nie jest już wspierane.'},{p:'Czy mogę mieć dostęp do danych analitycznych?',o:'Tak — dodaję klienta jako właściciela konta GA4, dzięki czemu masz pełny dostęp do danych.'}],par:'tarnobrzeg/strony-internetowe'},
{s:'tarnobrzeg/strony-internetowe/panel-administracyjny',t:'Panel administracyjny strony Tarnobrzeg',m:'Strony z panelem administracyjnym dla firm z Tarnobrzegu. Łatwa edycja treści bez programisty — WordPress, własne CMS.',h:'Panel administracyjny\nstrony internetowej w Tarnobrzegu',sub:'Buduję strony z intuicyjnym panelem, dzięki któremu możesz samodzielnie aktualizować treści, dodawać wpisy i zarządzać stroną.',o:'Panel administracyjny to interfejs pozwalający zarządzać treścią strony bez wiedzy technicznej. Używam sprawdzonych rozwiązań CMS dostosowanych do potrzeb konkretnej firmy. Każdą wdrożoną stronę przekazuję z szkoleniem z obsługi panelu.',k:['Niezależność od programisty przy zmianach treści','Łatwe dodawanie aktualności, usług i zdjęć','Zarządzanie realizacjami i ofertą','Możliwość szybkiej aktualizacji cen i danych kontaktowych'],f:[{p:'Jak trudny w obsłudze jest panel administracyjny?',o:'Stosuję rozwiązania intuicyjne — typowe aktualizacje treści zajmują kilka minut bez wiedzy technicznej.'},{p:'Czy mogę dodawać nowe podstrony samodzielnie?',o:'Tak, system umożliwia tworzenie nowych stron, wpisów blogowych i galerii.'}],par:'tarnobrzeg/strony-internetowe'},
{s:'tarnobrzeg/strony-internetowe/ssl-hosting-kopie-zapasowe',t:'SSL, hosting i kopie zapasowe Tarnobrzeg',m:'Certyfikat SSL, szybki hosting i automatyczne kopie zapasowe dla stron firm z Tarnobrzegu. Bezpieczeństwo i dostępność 99,9%.',h:'SSL, hosting i kopie zapasowe\ndla stron firm z Tarnobrzegu',sub:'Zapewniam stronie certyfikat SSL, stabilny hosting z SLA 99,9% i automatyczne codzienne kopie zapasowe.',o:'Bezpieczeństwo i niezawodność strony to podstawa. Certyfikat SSL szyfruje połączenie (kłódka w przeglądarce) i jest wymagany przez Google. Hosting na wydajnych serwerach zapewnia szybkie ładowanie, a automatyczne kopie zapasowe chronią przed utratą danych.',k:['Zabezpieczenie danych klientów (RODO)','Wyższe pozycje w Google (SSL jako czynnik rankingowy)','Ochrona przed utratą treści i danych','Szybkie przywrócenie strony po awarii'],f:[{p:'Co się stanie gdy strona będzie zaatakowana?',o:'Dzięki regularnym kopiom zapasowym mogę przywrócić stronę do stanu sprzed ataku w ciągu kilku godzin.'},{p:'Czy certyfikat SSL jest konieczny?',o:'Tak — przeglądarki oznaczają strony bez SSL jako niebezpieczne, a Google preferuje strony z SSL.'}],par:'tarnobrzeg/strony-internetowe'},
{s:'tarnobrzeg/strony-internetowe/formularze-kontaktowe',t:'Formularze kontaktowe na stronie Tarnobrzeg',m:'Formularze kontaktowe z powiadomieniami dla stron firm z Tarnobrzegu. Bezpieczne, z ochroną antyspamową i potwierdzeniami.',h:'Formularze kontaktowe\nna stronie firmowej w Tarnobrzegu',sub:'Wdrażam formularze kontaktowe, które działają niezawodnie — z powiadomieniami email, ochroną antyspamową i potwierdzeniami dla klientów.',o:'Formularz kontaktowy to jedno z najważniejszych narzędzi pozyskiwania leadów na stronie. Buduję formularze z ochroną antyspamową (reCAPTCHA), automatycznym potwierdzeniem dla klienta i natychmiastowym powiadomieniem dla firmy.',k:['Każde zapytanie trafia natychmiast do skrzynki','Klient dostaje automatyczne potwierdzenie','Ochrona przed spamem i botami','Możliwość przekierowania na stronę dziękujemy po wysłaniu'],f:[{p:'Czy formularz może wysyłać zapytanie na kilka adresów?',o:'Tak — mogę skonfigurować kopie powiadomień na dowolną liczbę adresów email.'},{p:'Czy dane z formularza są bezpieczne?',o:'Tak — używam szyfrowania SSL i nie przechowuję danych dłużej niż to konieczne.'}],par:'tarnobrzeg/strony-internetowe'},
{s:'tarnobrzeg/strony-internetowe/automatyzacja-follow-up-po-formularzu',t:'Automatyzacja follow-up po formularzu Tarnobrzeg',m:'Automatyczny follow-up po wypełnieniu formularza na stronie dla firm z Tarnobrzegu. Sekwencje email, SMS, integracje CRM.',h:'Automatyzacja follow-up\npo formularzu w Tarnobrzegu',sub:'Po każdym zapytaniu z formularza automatycznie uruchamiam sekwencję follow-up — email, SMS lub powiadomienie w CRM.',o:'Wielu klientów traci leady, bo za wolno odpowiada na zapytania. Automatyzacja follow-up rozwiązuje ten problem: zaraz po wypełnieniu formularza klient dostaje wiadomość powitalną, a firma — powiadomienie z pełnymi danymi do szybkiego kontaktu.',k:['Natychmiastowa odpowiedź dla klienta (budowanie zaufania)','Zero przeoczonych zapytań','Automatyczne zapisanie leada do CRM','Wyższy wskaźnik zamknięcia sprzedaży'],f:[{p:'Jak szybko wysyłany jest automatyczny follow-up?',o:'Natychmiast po wysłaniu formularza — zwykle w ciągu kilku sekund.'},{p:'Czy mogę dostosować treść wiadomości follow-up?',o:'Tak — treść każdej wiadomości automatycznej jest ustalana z klientem.'}],par:'tarnobrzeg/strony-internetowe'},
{s:'tarnobrzeg/strony-internetowe/optymalizacja-pod-generative-search',t:'Optymalizacja strony pod Generative Search Tarnobrzeg',m:'Optymalizacja stron firmowych pod AI Overviews i Generative Search Google dla firm z Tarnobrzegu. Strukturyzowane dane, E-E-A-T.',h:'Optymalizacja strony\npod Generative Search w Tarnobrzegu',sub:'Przygotowuję strony firm z Tarnobrzegu na erę AI w wyszukiwarce — Generative Search i AI Overviews Google.',o:'Google coraz częściej wyświetla odpowiedzi generowane przez AI zamiast tradycyjnych wyników. Optymalizacja pod Generative Search polega na tworzeniu treści wysokiej jakości z wyraźnym autorstwem (E-E-A-T), wdrożeniu schema markup i strukturyzowaniu informacji w formacie przystępnym dla modeli językowych.',k:['Widoczność w nowym formacie wyników Google','Cytowanie firmy przez AI Overviews','Przyszłościowa optymalizacja strony','Budowanie autorytetu E-E-A-T w branży'],f:[{p:'Czym są AI Overviews Google?',o:'AI Overviews to odpowiedzi generowane przez AI wyświetlane na górze wyników wyszukiwania. Firmy cytowane w AI Overviews zyskują ogromną widoczność.'},{p:'Jak już teraz przygotować stronę na AI Search?',o:'Przez tworzenie szczegółowych treści eksperckich, wdrożenie schema i budowanie autorytetu tematycznego.'}],par:'tarnobrzeg/strony-internetowe'},
];

// SEO subpages
sub3.push(...[
{s:'tarnobrzeg/seo/audyt-seo',t:'Audyt SEO Tarnobrzeg',m:'Audyt SEO strony dla firm z Tarnobrzegu. Analiza techniczna, treści, linków i widoczności w Google. Raport z rekomendacjami.',h:'Audyt SEO\ndla firm z Tarnobrzegu',sub:'Przeprowadzam kompleksowy audyt SEO, który pokazuje co na stronie blokuje wzrost pozycji w Google.',o:'Audyt SEO to punkt startowy każdej kampanii pozycjonowania. Analizuję technikalia strony, strukturę treści, jakość linków, prędkość ładowania i widoczność na frazy kluczowe. Efektem jest szczegółowy raport z priorytetami do wdrożenia.',k:['Jasny obraz stanu SEO strony','Lista błędów blokujących pozycje','Konkretne rekomendacje do wdrożenia','Punkt odniesienia do mierzenia postępów'],f:[{p:'Co zawiera raport z audytu SEO?',o:'Analizę techniczną, treści, linków, szybkości, mobile i widoczności na frazy — z oceną priorytetu każdego problemu.'},{p:'Czy audyt SEO jest potrzebny co roku?',o:'Zalecam audyt co 6-12 miesięcy i po każdej większej aktualizacji algorytmu Google.'}],par:'tarnobrzeg/seo'},
{s:'tarnobrzeg/seo/analiza-konkurencji-lokalnej',t:'Analiza konkurencji lokalnej SEO Tarnobrzeg',m:'Analiza konkurencji lokalnej SEO dla firm z Tarnobrzegu. Sprawdź co robią liderzy w Twoim rynku i jak ich wyprzedzić.',h:'Analiza konkurencji lokalnej\nSEO w Tarnobrzegu',sub:'Badam strategie SEO Twoich lokalnych konkurentów w Tarnobrzegu — i pokazuję jak ich wyprzedzić w wynikach Google.',o:'Analiza konkurencji SEO pozwala zrozumieć, dlaczego inne firmy z Tarnobrzegu są wyżej w Google. Badamy ich słowa kluczowe, strukturę treści, profil linków i optymalizację lokalną, żeby zidentyfikować luki i możliwości.',k:['Wiedza o lukach do wypełnienia w SEO','Inspiracja do strategii contentowej','Zrozumienie mocnych stron konkurentów','Lepszy plan działania na lokalnym rynku'],f:[{p:'Ile firm lokalnych powinno być w analizie konkurencji?',o:'Analizuję zwykle 3–5 najbliższych konkurentów widocznych na te same frazy co Ty.'},{p:'Jak często aktualizować analizę konkurencji?',o:'Raz na kwartał wystarczy, chyba że pojawi się nowy silny gracz na rynku.'}],par:'tarnobrzeg/seo'},
{s:'tarnobrzeg/seo/google-business-profile',t:'Google Business Profile Tarnobrzeg',m:'Optymalizacja i zarządzanie wizytówką Google Business Profile dla firm z Tarnobrzegu. Wyższe pozycje w Maps i lokalnych wynikach.',h:'Google Business Profile\ndla firm z Tarnobrzegu',sub:'Optymalizuję wizytówkę Google Moja Firma, żeby Twoja firma z Tarnobrzegu pojawiała się w Top 3 wyników lokalnych.',o:'Google Business Profile (dawniej Google Moja Firma) to najważniejsze narzędzie SEO lokalnego. Firmy z uzupełnionym i zoptymalizowanym profilem pojawiają się w mapach Google i lokalnym pakiecie 3 wyników — miejscu, które przyciąga największy ruch.',k:['Wyższe pozycje w Google Maps','Pojawienie się w lokalnym pakiecie 3','Więcej połączeń telefonicznych z Google','Profesjonalna prezentacja firmy z opiniami'],f:[{p:'Czy Google Business Profile jest darmowy?',o:'Tak, samo narzędzie jest bezpłatne. Płatna jest usługa zarządzania i optymalizacji profilu.'},{p:'Jak wpływają opinie Google na pozycje?',o:'Liczba i jakość opinii to istotny czynnik rankingowy w wynikach lokalnych.'}],par:'tarnobrzeg/seo'},
{s:'tarnobrzeg/seo/lokalne-slowa-kluczowe',t:'Lokalne słowa kluczowe SEO Tarnobrzeg',m:'Badanie i wdrożenie lokalnych słów kluczowych dla firm z Tarnobrzegu. Frazy z nazwą miasta przynoszące lokalnych klientów.',h:'Lokalne słowa kluczowe\ndla firm z Tarnobrzegu',sub:'Badam jakich fraz używają klienci szukając usług w Tarnobrzegu i wdrażam je w treściach strony.',o:'Lokalne słowa kluczowe to frazy zawierające nazwę miasta lub regionu, np. "fryzjer Tarnobrzeg" czy "strony internetowe Tarnobrzeg". Ich wdrożenie w treściach, meta tagach i strukturze URL to podstawa widoczności na lokalnym rynku.',k:['Trafienie na frazy używane przez lokalnych klientów','Niższa konkurencja niż na frazy ogólne','Wyższy wskaźnik konwersji (intencja zakupowa)','Wzrost lokalnego ruchu organicznego'],f:[{p:'Jak znaleźć najlepsze lokalne słowa kluczowe?',o:'Używam narzędzi jak Google Keyword Planner, Ahrefs i Google Search Console oraz analizy autouzupełniania Google.'},{p:'Ile fraz kluczowych powinna mieć moja strona?',o:'Jakość ważniejsza od ilości. Lepiej być na 20 trafnych frazach niż próbować atakować 200 nieskonwertujących.'}],par:'tarnobrzeg/seo'},
{s:'tarnobrzeg/seo/optymalizacja-techniczna-strony',t:'Optymalizacja techniczna strony SEO Tarnobrzeg',m:'Optymalizacja techniczna SEO dla stron firm z Tarnobrzegu. Szybkość, indeksacja, struktura URL, sitemap, robots.txt.',h:'Optymalizacja techniczna SEO\nstron firm z Tarnobrzegu',sub:'Naprawiam techniczne problemy SEO blokujące indeksację i pozycje Twojej strony w Google.',o:'Techniczne SEO to fundament widoczności w wyszukiwarce. Bez poprawnej indeksacji, szybkiego ładowania i czystej struktury nawet najlepsza treść nie dotrze do klientów. Analizuję i naprawiam problemy z crawlowaniem, duplikatami, przekierowaniami i szybkością.',k:['Prawidłowa indeksacja wszystkich podstron','Eliminacja błędów 404 i przekierowań łańcuchowych','Szybsze ładowanie wpływające na ranking','Lepsza architektura strony dla Googlebot'],f:[{p:'Co to jest plik robots.txt i sitemap.xml?',o:'Robots.txt wskazuje Googlebotowi które podstrony indeksować, a sitemap.xml to lista wszystkich podstron do zaindeksowania.'},{p:'Jak sprawdzić błędy techniczne SEO na stronie?',o:'Google Search Console, Screaming Frog i Ahrefs Site Audit to narzędzia do wykrywania problemów technicznych.'}],par:'tarnobrzeg/seo'},
{s:'tarnobrzeg/seo/tworzenie-tresci-seo',t:'Tworzenie treści SEO Tarnobrzeg',m:'Tworzenie treści SEO dla stron firm z Tarnobrzegu. Teksty usługowe, opisy, landing pages zoptymalizowane pod lokalne frazy kluczowe.',h:'Tworzenie treści SEO\ndla firm z Tarnobrzegu',sub:'Piszę treści zoptymalizowane pod frazy lokalne, które pozycjonują stronę Twojej firmy w Tarnobrzegu.',o:'Wartościowe treści SEO to jeden z najsilniejszych czynników rankingowych. Tworzę teksty na strony usługowe, podstrony lokalne i artykuły blogowe, które są zoptymalizowane pod frazy kluczowe, ale przede wszystkim napisane z myślą o kliencie.',k:['Wyższe pozycje na frazy usługowe i lokalne','Więcej organicznego ruchu bez kosztów reklamy','Treści odpowiadające na pytania klientów','Budowanie autorytetu tematycznego w branży'],f:[{p:'Czy treści SEO brzmią naturalnie?',o:'Tak — piszę przede wszystkim dla ludzi, a optymalizacja pod wyszukiwarki jest naturalnie wbudowana w treść.'},{p:'Jak długo powinna mieć tekst SEO?',o:'Zależy od tematu i konkurencji. Zwykle 800–2000 słów. Ważniejsza jest jakość i kompletność informacji.'}],par:'tarnobrzeg/seo'},
{s:'tarnobrzeg/seo/landing-page-lokalne',t:'Landing page lokalne SEO Tarnobrzeg',m:'Landing pages lokalne dla firm z Tarnobrzegu. Dedykowane podstrony pod frazy lokalnych klientów zwiększające widoczność i konwersję.',h:'Lokalne landing pages\ndla firm z Tarnobrzegu',sub:'Tworzę dedykowane landing pages pod frazy lokalne, które przyciągają klientów szukających usług w Tarnobrzegu.',o:'Lokalne landing pages to podstrony tworzone specjalnie pod konkretne frazy lokalne, np. "hydraulik Tarnobrzeg" lub "księgowość Tarnobrzeg". Każda taka strona jest zoptymalizowana pod jedną frazę i ma jasne CTA prowadzące do kontaktu.',k:['Wyspecjalizowane podstrony na konkretne frazy','Wyższy wskaźnik konwersji od strony głównej','Możliwość atakowania dziesiątek lokalnych fraz','Mierzalne wyniki dla każdej podstrony'],f:[{p:'Ile landing pages lokalnych warto mieć?',o:'Tyle ile masz usług lub lokalizacji — każda kombinacja usługa+miasto może mieć własny landing page.'},{p:'Czy landing page różni się od zwykłej podstrony?',o:'Tak — landing page jest zoptymalizowany pod jedną frazę i jeden cel (np. wypełnienie formularza).'}],par:'tarnobrzeg/seo'},
{s:'tarnobrzeg/seo/link-building-lokalny',t:'Link building lokalny Tarnobrzeg',m:'Link building lokalny dla firm z Tarnobrzegu. Pozyskiwanie linków z lokalnych katalogów, portali regionalnych i branżowych.',h:'Link building lokalny\ndla firm z Tarnobrzegu',sub:'Pozyskuję wartościowe linki z lokalnych portali, katalogów branżowych i stron tarnobrzeskiego biznesu.',o:'Link building to pozyskiwanie linków zewnętrznych prowadzących do Twojej strony. W kontekście lokalnym skupiam się na katalogach branżowych, regionalnych portalach informacyjnych i partnerskich stronach firm. Każdy lokalny link wzmacnia autorytet strony w oczach Google.',k:['Wzrost autorytetu domeny (Domain Authority)','Wyższe pozycje na frazy lokalne','Nowe źródła ruchu z portali regionalnych','Budowanie sieci lokalnych powiązań'],f:[{p:'Ile linków potrzeba do widocznych efektów?',o:'Jakość ważniejsza od ilości. 10 linków z lokalnych, tematycznych stron jest więcej warte niż 100 ze spamowych katalogów.'},{p:'Czy kupowanie linków jest bezpieczne?',o:'Kupowanie linków jest niezgodne z wytycznymi Google i może skutkować penalizacją. Skupiam się na naturalnym pozyskiwaniu linków.'}],par:'tarnobrzeg/seo'},
{s:'tarnobrzeg/seo/zarzadzanie-opiniami-google',t:'Zarządzanie opiniami Google Tarnobrzeg',m:'Zarządzanie opiniami Google Maps dla firm z Tarnobrzegu. Zbieranie pozytywnych opinii, odpowiadanie, budowanie reputacji online.',h:'Zarządzanie opiniami Google\ndla firm z Tarnobrzegu',sub:'Pomagam firmom z Tarnobrzegu systematycznie zbierać opinie Google i budować silną reputację w Maps.',o:'Opinie Google to jeden z najważniejszych czynników wpływających na decyzje zakupowe i pozycje w Maps. Wdrażam strategie zbierania opinii od zadowolonych klientów, szablony odpowiedzi i monitoring nowych recenzji.',k:['Wyższy rating = więcej klientów','Poprawa widoczności w Google Maps','Budowanie zaufania do marki lokalnej','Aktywna ochrona reputacji online'],f:[{p:'Jak prosić klientów o opinie bez naruszania zasad Google?',o:'Można wysyłać linki do opinii przez email lub SMS po zakończeniu usługi. Nie można nagradzać za opinie ani prosić tylko wybranych klientów.'},{p:'Czy można usunąć negatywną opinię?',o:'Można zgłosić opinię naruszającą regulamin. Opinie prawdziwe, nawet negatywne, są trudne do usunięcia — lepiej na nie odpowiadać.'}],par:'tarnobrzeg/seo'},
{s:'tarnobrzeg/seo/raport-seo-miesieczny',t:'Miesięczny raport SEO Tarnobrzeg',m:'Miesięczny raport SEO dla firm z Tarnobrzegu. Pozycje, ruch organiczny, wyniki techniczne z komentarzem i rekomendacjami na kolejny miesiąc.',h:'Miesięczny raport SEO\ndla firm z Tarnobrzegu',sub:'Co miesiąc dostarczam czytelny raport pozycji, ruchu i postępów w SEO z rekomendacjami na kolejny miesiąc.',o:'Transparentność to podstawa współpracy SEO. Co miesiąc przygotowuję raport zawierający aktualne pozycje na ustalonych frazach, zmianę ruchu organicznego, postępy techniczne i plan działań na kolejny okres.',k:['Pełna transparentność działań SEO','Jasny obraz postępów i trendów','Rekomendacje oparte na danych','Możliwość oceny ROI z inwestycji w SEO'],f:[{p:'Co zawiera miesięczny raport SEO?',o:'Pozycje na frazach kluczowych, ruch organiczny, zdarzenia techniczne, zbudowane linki i plan na kolejny miesiąc.'},{p:'Jak często powinienem sprawdzać pozycje?',o:'Codzienne sprawdzanie pozycji to za często — fluktuacje są normalne. Miesięczny raport daje lepszy obraz trendu.'}],par:'tarnobrzeg/seo'},
]);

// GOOGLE ADS subpages
sub3.push(...[
{s:'tarnobrzeg/google-ads/audyt-konta-google-ads',t:'Audyt konta Google Ads Tarnobrzeg',m:'Audyt konta Google Ads dla firm z Tarnobrzegu. Analiza kampanii, słów kluczowych, konwersji i marnotrawionego budżetu.',h:'Audyt konta Google Ads\ndla firm z Tarnobrzegu',sub:'Sprawdzam konto Google Ads pod kątem błędów, marnotrawionego budżetu i możliwości poprawy wyników.',o:'Audyt Google Ads to analiza istniejącego konta pod kątem struktury kampanii, trafności słów kluczowych, jakości reklam, ustawień targetowania i śledzenia konwersji. Efektem jest lista konkretnych zmian do wdrożenia.',k:['Identyfikacja marnotrawionego budżetu','Lista konkretnych poprawek z priorytetem','Lepsza jakość reklam i niższy CPC','Punkt wyjścia do skutecznej optymalizacji'],f:[{p:'Co sprawdzam podczas audytu konta Google Ads?',o:'Strukturę kampanii, trafność słów, wykluczające słowa kluczowe, stawki, rozszerzenia, strony docelowe i śledzenie konwersji.'},{p:'Ile trwa audyt konta Google Ads?',o:'Audyt podstawowego konta zajmuje zwykle 2–3 dni robocze.'}],par:'tarnobrzeg/google-ads'},
{s:'tarnobrzeg/google-ads/konfiguracja-nowego-konta-google-ads',t:'Konfiguracja konta Google Ads Tarnobrzeg',m:'Konfiguracja nowego konta Google Ads dla firm z Tarnobrzegu. Struktura kampanii, konwersje, grupy reklam i ustawienia lokalne.',h:'Konfiguracja konta Google Ads\ndla firm z Tarnobrzegu',sub:'Buduję konto Google Ads od zera — z prawidłową strukturą, śledzeniem konwersji i ustawieniami lokalnymi dla Tarnobrzegu.',o:'Dobrze zbudowane konto Google Ads to fundament skutecznych kampanii. Tworzę strukturę opartą na grupach reklam dopasowanych do intencji, konfiguruję śledzenie konwersji i ustawiam targetowanie geograficzne na Tarnobrzeg i okolice.',k:['Konto gotowe do skutecznych kampanii od pierwszego dnia','Prawidłowe śledzenie każdej konwersji','Struktura ułatwiająca późniejszą optymalizację','Unikanie błędów kosztujących budżet'],f:[{p:'Jak długo trwa konfiguracja nowego konta?',o:'Konfiguracja konta z 2–3 kampaniami zajmuje zwykle 3–5 dni roboczych.'},{p:'Czy Google daje bonus na start nowego konta?',o:'Google często oferuje kupony startowe dla nowych kont — informuję o aktualnych ofertach podczas onboardingu.'}],par:'tarnobrzeg/google-ads'},
{s:'tarnobrzeg/google-ads/badanie-slow-kluczowych',t:'Badanie słów kluczowych Google Ads Tarnobrzeg',m:'Badanie słów kluczowych do kampanii Google Ads dla firm z Tarnobrzegu. Frazy kupujące, wykluczające, lokalne i branżowe.',h:'Badanie słów kluczowych\ndo kampanii Google Ads w Tarnobrzegu',sub:'Badam jakie frazy wpisują klienci szukający Twoich usług w Tarnobrzegu — i kieruję kampanię dokładnie na te słowa.',o:'Dobór słów kluczowych decyduje o sukcesie kampanii Google Ads. Analizuję wolumen wyszukiwań, konkurencję, CPC i intencję zakupową za każdą frazą. Wybieram słowa przynoszące konwersje, nie tylko kliknięcia, i buduję listę wykluczających słów kluczowych.',k:['Reklamy wyświetlane na właściwych frazach','Wyższy wskaźnik konwersji kampanii','Niższy koszt za kliknięcie (CPC)','Eliminacja fraz marnujących budżet'],f:[{p:'Czym są wykluczające słowa kluczowe?',o:'Frazy, na które nie chcemy pokazywać reklam. Np. firma instalacyjna wyklucza słowo "darmowy", żeby nie płacić za kliknięcia niezainteresowanych klientów.'},{p:'Ile słów kluczowych powinno być w kampanii?',o:'Lepiej mieć 20–50 trafnych słów niż 500 niezwiązanych. Precyzja ważniejsza od ilości.'}],par:'tarnobrzeg/google-ads'},
{s:'tarnobrzeg/google-ads/kreacje-reklamowe-google-ads',t:'Kreacje reklamowe Google Ads Tarnobrzeg',m:'Tworzenie skutecznych kreacji reklamowych Google Ads dla firm z Tarnobrzegu. Reklamy tekstowe, responsywne i displayowe.',h:'Kreacje reklamowe Google Ads\ndla firm z Tarnobrzegu',sub:'Piszę i projektuję skuteczne reklamy Google Ads, które przyciągają kliknięcia i konwertują na zapytania.',o:'Treść reklamy decyduje o tym, czy użytkownik kliknie właśnie Twoją ofertę. Tworzę reklamy tekstowe, responsywne i displayowe z silnymi nagłówkami, wyróżnikami oferty i klarownym wezwaniem do działania dopasowanym do fraz kluczowych.',k:['Wyższy CTR (wskaźnik klikalności)','Lepsza ocena jakości reklamy (Quality Score)','Niższy CPC dzięki wyższemu Quality Score','Reklamy wyróżniające się na tle konkurencji'],f:[{p:'Ile wariantów reklam powinienem testować?',o:'Minimum 3–5 wariantów na grupę reklam. Google sam wybiera najlepiej konwertujące.'},{p:'Jak często aktualizować kreacje reklamowe?',o:'Regularnie — w oparciu o dane z testów. Zwykle co 4–8 tygodni wprowadzam nowe warianty.'}],par:'tarnobrzeg/google-ads'},
{s:'tarnobrzeg/google-ads/targetowanie-lokalne-google-ads',t:'Targetowanie lokalne Google Ads Tarnobrzeg',m:'Precyzyjne targetowanie lokalne kampanii Google Ads dla firm z Tarnobrzegu. Geotargetowanie, promień, harmonogram reklam.',h:'Targetowanie lokalne Google Ads\ndla firm z Tarnobrzegu',sub:'Ustawiam reklamy Google Ads tak, żeby docierały dokładnie do klientów z Tarnobrzegu i wybranego promienia.',o:'Targetowanie geograficzne pozwala wyświetlać reklamy tylko użytkownikom w Tarnobrzegu lub w określonym promieniu. Dla lokalnych firm to kluczowe — płacisz tylko za kliknięcia od realnych potencjalnych klientów, a nie z odległych regionów.',k:['Budżet trafia tylko do lokalnych klientów','Wyższy współczynnik konwersji lokalnych reklam','Możliwość wyłączenia reklam poza godzinami pracy','Personalizacja komunikatu dla Tarnobrzegu'],f:[{p:'Czy mogę targetować dokładnie jeden kod pocztowy?',o:'Tak — Google Ads pozwala na targetowanie po kodach pocztowych, miastach, promieniu od lokalizacji i własnych obszarach.'},{p:'Jak ustawić reklamy tylko na godziny pracy?',o:'W ustawieniach harmonogramu kampanii można dokładnie określić dni i godziny wyświetlania reklam.'}],par:'tarnobrzeg/google-ads'},
{s:'tarnobrzeg/google-ads/sledzenie-konwersji-google-ads',t:'Śledzenie konwersji Google Ads Tarnobrzeg',m:'Konfiguracja śledzenia konwersji Google Ads dla firm z Tarnobrzegu. Formularze, telefony, zakupy — mierz co przynosi klientów.',h:'Śledzenie konwersji Google Ads\ndla firm z Tarnobrzegu',sub:'Konfiguruję śledzenie konwersji, żebyś dokładnie wiedział które słowa kluczowe i reklamy przynoszą klientów.',o:'Bez śledzenia konwersji kampania Google Ads działa w ciemno — nie wiesz co przynosi leady. Konfiguruję śledzenie wypełnień formularzy, połączeń telefonicznych, wizyt w sklepie i zakupów w e-commerce.',k:['Pełna wiedza które reklamy przynoszą klientów','Podstawa do inteligentnego zarządzania stawkami','Możliwość obliczenia ROI każdej kampanii','Dane do optymalizacji i skalowania kampanii'],f:[{p:'Co to jest konwersja w Google Ads?',o:'Konwersja to pożądana akcja użytkownika — np. wypełnienie formularza, rozmowa telefoniczna lub zakup w sklepie.'},{p:'Czy mogę śledzić połączenia telefoniczne z reklam?',o:'Tak — Google Ads oferuje śledzenie połączeń przez dynamiczne numery telefoniczne.'}],par:'tarnobrzeg/google-ads'},
{s:'tarnobrzeg/google-ads/optymalizacja-kampanii-google-ads',t:'Optymalizacja kampanii Google Ads Tarnobrzeg',m:'Regularna optymalizacja kampanii Google Ads dla firm z Tarnobrzegu. Testy, stawki, słowa kluczowe, jakość reklam.',h:'Optymalizacja kampanii Google Ads\ndla firm z Tarnobrzegu',sub:'Co tydzień optymalizuję kampanie Google Ads, żeby przy tym samym budżecie dostarczały coraz więcej klientów.',o:'Optymalizacja kampanii Google Ads to ciągły proces: testowanie nowych reklam, dostosowywanie stawek, rozszerzanie list wykluczeń, analiza danych demograficznych i modyfikowanie targetowania. Regularny nadzór to różnica między kampanią kosztującą a zarabiającą.',k:['Coraz niższy koszt za konwersję','Lepsze wykorzystanie budżetu reklamowego','Wzrost ROAS przy tym samym spend','Systematyczne eliminowanie słabych elementów'],f:[{p:'Jak często powinna być optymalizowana kampania?',o:'Dla kampanii z budżetem 500+ zł/dzień — codziennie. Dla mniejszych — 2-3 razy w tygodniu.'},{p:'Czym jest Quality Score w Google Ads?',o:'Ocena jakości (1–10) przyznawana słowom kluczowym. Wyższy Quality Score = niższy CPC i lepsze pozycje reklam.'}],par:'tarnobrzeg/google-ads'},
{s:'tarnobrzeg/google-ads/remarketing-google-ads',t:'Remarketing Google Ads Tarnobrzeg',m:'Kampanie remarketingowe Google Ads dla firm z Tarnobrzegu. Odzyskiwanie odwiedzających stronę i porzuconych koszyków.',h:'Remarketing Google Ads\ndla firm z Tarnobrzegu',sub:'Docieramy ponownie do osób, które odwiedziły Twoją stronę — żeby przypomnieć im o Twojej ofercie i zachęcić do kontaktu.',o:'Remarketing pozwala wyświetlać reklamy osobom, które już odwiedziły Twoją stronę. To najtańszy i najskuteczniejszy sposób na odzyskanie leadów — osoba, która była na stronie, ma 3x wyższe prawdopodobieństwo konwersji niż nowy odwiedzający.',k:['Wyższy ROAS niż kampanie prospektingowe','Niska konkurencja (własna lista odbiorców)','Przypomnienie oferty osobom zainteresowanym','Odzyskiwanie porzuconych koszyków w e-commerce'],f:[{p:'Jak działa remarketing Google Ads?',o:'Kod remarketingowy (tag) na stronie zbiera listy odwiedzających. Reklamy remarketingowe trafiają do tych osób w sieci display i wynikach wyszukiwania.'},{p:'Czy remarketing nie irytuje użytkowników?',o:'Dobrze ustawiony remarketing (z frequency cap i segmentacją list) jest postrzegany jako przydatne przypomnienie, nie spam.'}],par:'tarnobrzeg/google-ads'},
{s:'tarnobrzeg/google-ads/raport-google-ads-roas',t:'Raport Google Ads i ROAS Tarnobrzeg',m:'Miesięczny raport kampanii Google Ads dla firm z Tarnobrzegu. Wyniki, koszty, konwersje, ROAS i rekomendacje na kolejny miesiąc.',h:'Raport Google Ads i ROAS\ndla firm z Tarnobrzegu',sub:'Co miesiąc dostarczam czytelny raport kampanii — koszty, konwersje, ROAS i plan optymalizacji.',o:'Transparentny raport miesięczny to standard współpracy. Dostarczam zestawienie wszystkich kluczowych wskaźników: wydany budżet, kliknięcia, konwersje, koszt za konwersję i ROAS. Każdy raport zawiera komentarz i plan działań na kolejny miesiąc.',k:['Pełna transparentność wydatków i wyników','Łatwe obliczenie ROI z kampanii','Jasne rekomendacje co zmieniać','Dokumentacja postępów i trendów'],f:[{p:'Co to jest ROAS?',o:'ROAS (Return on Ad Spend) to zwrot z wydatków na reklamę. ROAS 400% oznacza, że za każdą złotówkę wydaną na reklamę zarabiasz 4 złote przychodu.'},{p:'Jak często otrzymuję raporty?',o:'Raport miesięczny standardowo. Na życzenie mogę dostarczać cotygodniowe zestawienia kluczowych wskaźników.'}],par:'tarnobrzeg/google-ads'},
]);

const insertAll = db.transaction(() => {
  for (const p of pages) {
    insert.run(p.slug, p.title, p.meta_description, p.h1, p.hero_subtitle, JSON.stringify(p.content_json));
  }
  for (const p of sub3) {
    insert.run(p.s, p.t, p.m, p.h, p.sub, JSON.stringify({ opis: p.o, korzysci: p.k, faq: p.f.map(f => ({pytanie: f.p || f.pytanie, odpowiedz: f.o || f.odpowiedz})), parent_cat: p.par }));
  }
});

insertAll();
const count = db.prepare('SELECT COUNT(*) as n FROM pages').get();
console.log('Total pages in DB:', count.n);
db.close();
